apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sqrbot-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sqrbot
    spec:
      containers:

        - name: sqrbot
          imagePullPolicy: "Always"
          image: "lsstsqre/sqrbot:latest"
          env:
            - name: HUBOT_NAME
              value: "sqrbot"
            - name: HUBOT_SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sqrbot-secrets
                  key: slack-token
            - name: HUBOT_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sqrbot-secrets
                  key: github-token
            - name: HUBOT_GITHUB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqrbot-secrets
                  key: github-password
            - name: HUBOT_GITHUB_USER
              valueFrom:
                secretKeyRef:
                  name: sqrbot-secrets
                  key: github-user
            - name: LSST_JIRA_USER
              valueFrom:
                secretKeyRef:
                  name: sqrbot-secrets
                  key: jira-user
            - name: LSST_JIRA_PWD
              valueFrom:
                secretKeyRef:
                  name: sqrbot-secrets
                  key: jira-password
            - name: HUBOT_LOG_LEVEL
              value: info
